name: Test And Validate

on:
    push:
        branches-ignore:
            - main
        paths:
            - '**.tf'

jobs:
    TestAndValidate:
        runs-on: ubuntu-latest

        name: 'Test and Validate'
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            WORKING_DIR: .

        steps:
            - uses: actions/checkout@v3

            - name: Init terraform
              id: init
              run: terraform init -backend=false
              working-directory: ${{ env.WORKING_DIR }}

            - name: Terraform format
              id: fmt
              run: terraform fmt -check -recursive
              working-directory: ${{ env.WORKING_DIR }}

            - name: Terraform validate
              id: validate
              run: terraform validate
              working-directory: ${{ env.WORKING_DIR }}

            - name: Tfsec
              id: tfsec
              uses: aquasecurity/tfsec-action@v1.0.0
              with:
                additional_args: --minimum-severity CRITICAL
                working_directory: ${{ env.WORKING_DIR }}

            - uses: terraform-linters/setup-tflint@v3
              name: Setup TFLint
              with:
                tflint_version: v0.44.1

            - name: Show version
              run: tflint --version

            - name: Init TFLint
              run: tflint --init
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Run TFLint
              run: tflint -f compact

